package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer idContact;
     private int idUtilisateur;
     private String contenu;
     private String temps;
     private int vu;
     private String tempsVu;
     private Integer idReponse;
     private int isDeleted;

    public Contact() {
    }

	
    public Contact(int idUtilisateur, String contenu, String temps, int vu, int isDeleted) {
        this.idUtilisateur = idUtilisateur;
        this.contenu = contenu;
        this.temps = temps;
        this.vu = vu;
        this.isDeleted = isDeleted;
    }
    public Contact(int idUtilisateur, String contenu, String temps, int vu, String tempsVu, Integer idReponse, int isDeleted) {
       this.idUtilisateur = idUtilisateur;
       this.contenu = contenu;
       this.temps = temps;
       this.vu = vu;
       this.tempsVu = tempsVu;
       this.idReponse = idReponse;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdContact() {
        return this.idContact;
    }
    
    public void setIdContact(Integer idContact) {
        this.idContact = idContact;
    }
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }
    public String getTemps() {
        return this.temps;
    }
    
    public void setTemps(String temps) {
        this.temps = temps;
    }
    public int getVu() {
        return this.vu;
    }
    
    public void setVu(int vu) {
        this.vu = vu;
    }
    public String getTempsVu() {
        return this.tempsVu;
    }
    
    public void setTempsVu(String tempsVu) {
        this.tempsVu = tempsVu;
    }
    public Integer getIdReponse() {
        return this.idReponse;
    }
    
    public void setIdReponse(Integer idReponse) {
        this.idReponse = idReponse;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


