package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * DocNotif generated by hbm2java
 */
public class DocNotif  implements java.io.Serializable {


     private Integer idDocNotif;
     private int idDocument;
     private int idNotification;
     private int isDeleted;

    public DocNotif() {
    }

    public DocNotif(int idDocument, int idNotification, int isDeleted) {
       this.idDocument = idDocument;
       this.idNotification = idNotification;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdDocNotif() {
        return this.idDocNotif;
    }
    
    public void setIdDocNotif(Integer idDocNotif) {
        this.idDocNotif = idDocNotif;
    }
    public int getIdDocument() {
        return this.idDocument;
    }
    
    public void setIdDocument(int idDocument) {
        this.idDocument = idDocument;
    }
    public int getIdNotification() {
        return this.idNotification;
    }
    
    public void setIdNotification(int idNotification) {
        this.idNotification = idNotification;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


