package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * DocObjetSn generated by hbm2java
 */
public class DocObjetSn  implements java.io.Serializable {


     private Integer idDocObjetSn;
     private int idDocObjet;
     private int idSn;
     private int isDeleted;

    public DocObjetSn() {
    }

    public DocObjetSn(int idDocObjet, int idSn, int isDeleted) {
       this.idDocObjet = idDocObjet;
       this.idSn = idSn;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdDocObjetSn() {
        return this.idDocObjetSn;
    }
    
    public void setIdDocObjetSn(Integer idDocObjetSn) {
        this.idDocObjetSn = idDocObjetSn;
    }
    public int getIdDocObjet() {
        return this.idDocObjet;
    }
    
    public void setIdDocObjet(int idDocObjet) {
        this.idDocObjet = idDocObjet;
    }
    public int getIdSn() {
        return this.idSn;
    }
    
    public void setIdSn(int idSn) {
        this.idSn = idSn;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


