package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private Integer idNotification;
     private String nomNotification;
     private int idUtilisateur;
     private String mode;
     private String evenement;
     private String dateEvenement;
     private String rappel;
     private int isDeleted;

    public Notification() {
    }

    public Notification(String nomNotification, int idUtilisateur, String mode, String evenement, String dateEvenement, String rappel, int isDeleted) {
       this.nomNotification = nomNotification;
       this.idUtilisateur = idUtilisateur;
       this.mode = mode;
       this.evenement = evenement;
       this.dateEvenement = dateEvenement;
       this.rappel = rappel;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdNotification() {
        return this.idNotification;
    }
    
    public void setIdNotification(Integer idNotification) {
        this.idNotification = idNotification;
    }
    public String getNomNotification() {
        return this.nomNotification;
    }
    
    public void setNomNotification(String nomNotification) {
        this.nomNotification = nomNotification;
    }
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }
    public String getMode() {
        return this.mode;
    }
    
    public void setMode(String mode) {
        this.mode = mode;
    }
    public String getEvenement() {
        return this.evenement;
    }
    
    public void setEvenement(String evenement) {
        this.evenement = evenement;
    }
    public String getDateEvenement() {
        return this.dateEvenement;
    }
    
    public void setDateEvenement(String dateEvenement) {
        this.dateEvenement = dateEvenement;
    }
    public String getRappel() {
        return this.rappel;
    }
    
    public void setRappel(String rappel) {
        this.rappel = rappel;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


