package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * TypeNature generated by hbm2java
 */
public class TypeNature  implements java.io.Serializable {


     private Integer idType;
     private int idNature;
     private String nomType;
     private int isDeleted;

    public TypeNature() {
    }

    public TypeNature(int idNature, String nomType, int isDeleted) {
       this.idNature = idNature;
       this.nomType = nomType;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public int getIdNature() {
        return this.idNature;
    }
    
    public void setIdNature(int idNature) {
        this.idNature = idNature;
    }
    public String getNomType() {
        return this.nomType;
    }
    
    public void setNomType(String nomType) {
        this.nomType = nomType;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


