package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * TypeAttachment generated by hbm2java
 */
public class TypeAttachment  implements java.io.Serializable {


     private Integer idTypeAttachment;
     private String typeAttachment;
     private String situationAttachment;
     private String nomAttachment;
     private int idStructure;
     private int idProjet;
     private int idNature;
     private int idDesignation;
     private int idType;
     private int isDeleted;

    public TypeAttachment() {
    }

    public TypeAttachment(String typeAttachment, String situationAttachment, String nomAttachment, int idStructure, int idProjet, int idNature, int idDesignation, int idType, int isDeleted) {
       this.typeAttachment = typeAttachment;
       this.situationAttachment = situationAttachment;
       this.nomAttachment = nomAttachment;
       this.idStructure = idStructure;
       this.idProjet = idProjet;
       this.idNature = idNature;
       this.idDesignation = idDesignation;
       this.idType = idType;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdTypeAttachment() {
        return this.idTypeAttachment;
    }
    
    public void setIdTypeAttachment(Integer idTypeAttachment) {
        this.idTypeAttachment = idTypeAttachment;
    }
    public String getTypeAttachment() {
        return this.typeAttachment;
    }
    
    public void setTypeAttachment(String typeAttachment) {
        this.typeAttachment = typeAttachment;
    }
    public String getSituationAttachment() {
        return this.situationAttachment;
    }
    
    public void setSituationAttachment(String situationAttachment) {
        this.situationAttachment = situationAttachment;
    }
    public String getNomAttachment() {
        return this.nomAttachment;
    }
    
    public void setNomAttachment(String nomAttachment) {
        this.nomAttachment = nomAttachment;
    }
    public int getIdStructure() {
        return this.idStructure;
    }
    
    public void setIdStructure(int idStructure) {
        this.idStructure = idStructure;
    }
    public int getIdProjet() {
        return this.idProjet;
    }
    
    public void setIdProjet(int idProjet) {
        this.idProjet = idProjet;
    }
    public int getIdNature() {
        return this.idNature;
    }
    
    public void setIdNature(int idNature) {
        this.idNature = idNature;
    }
    public int getIdDesignation() {
        return this.idDesignation;
    }
    
    public void setIdDesignation(int idDesignation) {
        this.idDesignation = idDesignation;
    }
    public int getIdType() {
        return this.idType;
    }
    
    public void setIdType(int idType) {
        this.idType = idType;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


