package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private Integer idUtilisateur;
     private int idMembre;
     private String username;
     private String password;
     private String hash;
     private int idStructure;
     private String role;
     private int isActive;
     private int isDeleted;

    public Utilisateur() {
    }

    public Utilisateur(int idMembre, String username, String password, String hash, int idStructure, String role, int isActive, int isDeleted) {
       this.idMembre = idMembre;
       this.username = username;
       this.password = password;
       this.hash = hash;
       this.idStructure = idStructure;
       this.role = role;
       this.isActive = isActive;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(Integer idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }
    public int getIdMembre() {
        return this.idMembre;
    }
    
    public void setIdMembre(int idMembre) {
        this.idMembre = idMembre;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    public int getIdStructure() {
        return this.idStructure;
    }
    
    public void setIdStructure(int idStructure) {
        this.idStructure = idStructure;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


