package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * Cv generated by hbm2java
 */
public class Cv  implements java.io.Serializable {


     private Integer idCv;
     private int idPersonne;
     private String nomDocument;
     private String lienDocument;
     private int isDeleted;

    public Cv() {
    }

    public Cv(int idPersonne, String nomDocument, String lienDocument, int isDeleted) {
       this.idPersonne = idPersonne;
       this.nomDocument = nomDocument;
       this.lienDocument = lienDocument;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdCv() {
        return this.idCv;
    }
    
    public void setIdCv(Integer idCv) {
        this.idCv = idCv;
    }
    public int getIdPersonne() {
        return this.idPersonne;
    }
    
    public void setIdPersonne(int idPersonne) {
        this.idPersonne = idPersonne;
    }
    public String getNomDocument() {
        return this.nomDocument;
    }
    
    public void setNomDocument(String nomDocument) {
        this.nomDocument = nomDocument;
    }
    public String getLienDocument() {
        return this.lienDocument;
    }
    
    public void setLienDocument(String lienDocument) {
        this.lienDocument = lienDocument;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


