package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * DesignationNature generated by hbm2java
 */
public class DesignationNature  implements java.io.Serializable {


     private Integer idDes;
     private int idNature;
     private String nomDes;
     private int isDeleted;

    public DesignationNature() {
    }

    public DesignationNature(int idNature, String nomDes, int isDeleted) {
       this.idNature = idNature;
       this.nomDes = nomDes;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdDes() {
        return this.idDes;
    }
    
    public void setIdDes(Integer idDes) {
        this.idDes = idDes;
    }
    public int getIdNature() {
        return this.idNature;
    }
    
    public void setIdNature(int idNature) {
        this.idNature = idNature;
    }
    public String getNomDes() {
        return this.nomDes;
    }
    
    public void setNomDes(String nomDes) {
        this.nomDes = nomDes;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


