package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * DocObjet generated by hbm2java
 */
public class DocObjet  implements java.io.Serializable {


     private Integer idDocObjet;
     private int idDocument;
     private int idObject;
     private String autreNom;
     private double autrePu;
     private String cond;
     private int isDeleted;

    public DocObjet() {
    }

    public DocObjet(int idDocument, int idObject, String autreNom, double autrePu, String cond, int isDeleted) {
       this.idDocument = idDocument;
       this.idObject = idObject;
       this.autreNom = autreNom;
       this.autrePu = autrePu;
       this.cond = cond;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdDocObjet() {
        return this.idDocObjet;
    }
    
    public void setIdDocObjet(Integer idDocObjet) {
        this.idDocObjet = idDocObjet;
    }
    public int getIdDocument() {
        return this.idDocument;
    }
    
    public void setIdDocument(int idDocument) {
        this.idDocument = idDocument;
    }
    public int getIdObject() {
        return this.idObject;
    }
    
    public void setIdObject(int idObject) {
        this.idObject = idObject;
    }
    public String getAutreNom() {
        return this.autreNom;
    }
    
    public void setAutreNom(String autreNom) {
        this.autreNom = autreNom;
    }
    public double getAutrePu() {
        return this.autrePu;
    }
    
    public void setAutrePu(double autrePu) {
        this.autrePu = autrePu;
    }
    public String getCond() {
        return this.cond;
    }
    
    public void setCond(String cond) {
        this.cond = cond;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


