package maps;
// Generated 9 sept. 2020 14:35:48 by Hibernate Tools 4.3.1



/**
 * Projet generated by hbm2java
 */
public class Projet  implements java.io.Serializable {


     private Integer idProjet;
     private int idStructure;
     private String nomProjet;
     private int isDeleted;

    public Projet() {
    }

    public Projet(int idStructure, String nomProjet, int isDeleted) {
       this.idStructure = idStructure;
       this.nomProjet = nomProjet;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdProjet() {
        return this.idProjet;
    }
    
    public void setIdProjet(Integer idProjet) {
        this.idProjet = idProjet;
    }
    public int getIdStructure() {
        return this.idStructure;
    }
    
    public void setIdStructure(int idStructure) {
        this.idStructure = idStructure;
    }
    public String getNomProjet() {
        return this.nomProjet;
    }
    
    public void setNomProjet(String nomProjet) {
        this.nomProjet = nomProjet;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


